apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kwg6z755h-python
  janus-idp.io/tekton: kwg6z755h-python
  backstage.io/kubernetes-id: kwg6z755h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kwg6z755h-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
